/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsuariosRouteImport } from './routes/dashboard.usuarios'
import { Route as DashboardNotificacoesRouteImport } from './routes/dashboard.notificacoes'
import { Route as DashboardJogosRouteImport } from './routes/dashboard.jogos'
import { Route as DashboardDicasRouteImport } from './routes/dashboard.dicas'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as ApiPublicHooksRefreshDailyMatchesRouteImport } from './routes/api/public/hooks/refresh-daily-matches'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsuariosRoute = DashboardUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificacoesRoute = DashboardNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJogosRoute = DashboardJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDicasRoute = DashboardDicasRouteImport.update({
  id: '/dicas',
  path: '/dicas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicHooksRefreshDailyMatchesRoute =
  ApiPublicHooksRefreshDailyMatchesRouteImport.update({
    id: '/api/public/hooks/refresh-daily-matches',
    path: '/api/public/hooks/refresh-daily-matches',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/dicas': typeof DashboardDicasRoute
  '/dashboard/jogos': typeof DashboardJogosRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/refresh-daily-matches': typeof ApiPublicHooksRefreshDailyMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/dicas': typeof DashboardDicasRoute
  '/dashboard/jogos': typeof DashboardJogosRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/hooks/refresh-daily-matches': typeof ApiPublicHooksRefreshDailyMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/dicas': typeof DashboardDicasRoute
  '/dashboard/jogos': typeof DashboardJogosRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/refresh-daily-matches': typeof ApiPublicHooksRefreshDailyMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/configuracoes'
    | '/dashboard/dicas'
    | '/dashboard/jogos'
    | '/dashboard/notificacoes'
    | '/dashboard/usuarios'
    | '/dashboard/'
    | '/api/public/hooks/refresh-daily-matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/configuracoes'
    | '/dashboard/dicas'
    | '/dashboard/jogos'
    | '/dashboard/notificacoes'
    | '/dashboard/usuarios'
    | '/dashboard'
    | '/api/public/hooks/refresh-daily-matches'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/configuracoes'
    | '/dashboard/dicas'
    | '/dashboard/jogos'
    | '/dashboard/notificacoes'
    | '/dashboard/usuarios'
    | '/dashboard/'
    | '/api/public/hooks/refresh-daily-matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiPublicHooksRefreshDailyMatchesRoute: typeof ApiPublicHooksRefreshDailyMatchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usuarios': {
      id: '/dashboard/usuarios'
      path: '/usuarios'
      fullPath: '/dashboard/usuarios'
      preLoaderRoute: typeof DashboardUsuariosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notificacoes': {
      id: '/dashboard/notificacoes'
      path: '/notificacoes'
      fullPath: '/dashboard/notificacoes'
      preLoaderRoute: typeof DashboardNotificacoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jogos': {
      id: '/dashboard/jogos'
      path: '/jogos'
      fullPath: '/dashboard/jogos'
      preLoaderRoute: typeof DashboardJogosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dicas': {
      id: '/dashboard/dicas'
      path: '/dicas'
      fullPath: '/dashboard/dicas'
      preLoaderRoute: typeof DashboardDicasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/hooks/refresh-daily-matches': {
      id: '/api/public/hooks/refresh-daily-matches'
      path: '/api/public/hooks/refresh-daily-matches'
      fullPath: '/api/public/hooks/refresh-daily-matches'
      preLoaderRoute: typeof ApiPublicHooksRefreshDailyMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardDicasRoute: typeof DashboardDicasRoute
  DashboardJogosRoute: typeof DashboardJogosRoute
  DashboardNotificacoesRoute: typeof DashboardNotificacoesRoute
  DashboardUsuariosRoute: typeof DashboardUsuariosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardDicasRoute: DashboardDicasRoute,
  DashboardJogosRoute: DashboardJogosRoute,
  DashboardNotificacoesRoute: DashboardNotificacoesRoute,
  DashboardUsuariosRoute: DashboardUsuariosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiPublicHooksRefreshDailyMatchesRoute:
    ApiPublicHooksRefreshDailyMatchesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
