/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsuariosRouteImport } from './routes/dashboard.usuarios'
import { Route as DashboardNotificacoesRouteImport } from './routes/dashboard.notificacoes'
import { Route as DashboardJogosRouteImport } from './routes/dashboard.jogos'
import { Route as DashboardDicasRouteImport } from './routes/dashboard.dicas'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as ApiPublicFeaturesRouteImport } from './routes/api/public/features'
import { Route as ApiPublicTeamImageIdRouteImport } from './routes/api/public/team-image.$id'
import { Route as ApiPublicMobileTicketsRouteImport } from './routes/api/public/mobile/tickets'
import { Route as ApiPublicMobileSignupRouteImport } from './routes/api/public/mobile/signup'
import { Route as ApiPublicMobileLoginRouteImport } from './routes/api/public/mobile/login'
import { Route as ApiPublicHooksRefreshDailyMatchesRouteImport } from './routes/api/public/hooks/refresh-daily-matches'
import { Route as ApiPublicHooksPollLiveNotificationsRouteImport } from './routes/api/public/hooks/poll-live-notifications'
import { Route as ApiPublicDebugApiKeyRouteImport } from './routes/api/public/debug/api-key'
import { Route as ApiPublicMobileTicketsIdRouteImport } from './routes/api/public/mobile/tickets.$id'
import { Route as ApiPublicMobileNotificationsLiveRouteImport } from './routes/api/public/mobile/notifications/live'
import { Route as ApiPublicMobileMatchesTodayRouteImport } from './routes/api/public/mobile/matches/today'
import { Route as ApiPublicMobileMatchesLiveRouteImport } from './routes/api/public/mobile/matches/live'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsuariosRoute = DashboardUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificacoesRoute = DashboardNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJogosRoute = DashboardJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDicasRoute = DashboardDicasRouteImport.update({
  id: '/dicas',
  path: '/dicas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicFeaturesRoute = ApiPublicFeaturesRouteImport.update({
  id: '/api/public/features',
  path: '/api/public/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTeamImageIdRoute = ApiPublicTeamImageIdRouteImport.update({
  id: '/api/public/team-image/$id',
  path: '/api/public/team-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMobileTicketsRoute = ApiPublicMobileTicketsRouteImport.update({
  id: '/api/public/mobile/tickets',
  path: '/api/public/mobile/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMobileSignupRoute = ApiPublicMobileSignupRouteImport.update({
  id: '/api/public/mobile/signup',
  path: '/api/public/mobile/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMobileLoginRoute = ApiPublicMobileLoginRouteImport.update({
  id: '/api/public/mobile/login',
  path: '/api/public/mobile/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshDailyMatchesRoute =
  ApiPublicHooksRefreshDailyMatchesRouteImport.update({
    id: '/api/public/hooks/refresh-daily-matches',
    path: '/api/public/hooks/refresh-daily-matches',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPollLiveNotificationsRoute =
  ApiPublicHooksPollLiveNotificationsRouteImport.update({
    id: '/api/public/hooks/poll-live-notifications',
    path: '/api/public/hooks/poll-live-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDebugApiKeyRoute = ApiPublicDebugApiKeyRouteImport.update({
  id: '/api/public/debug/api-key',
  path: '/api/public/debug/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMobileTicketsIdRoute =
  ApiPublicMobileTicketsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicMobileTicketsRoute,
  } as any)
const ApiPublicMobileNotificationsLiveRoute =
  ApiPublicMobileNotificationsLiveRouteImport.update({
    id: '/api/public/mobile/notifications/live',
    path: '/api/public/mobile/notifications/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMobileMatchesTodayRoute =
  ApiPublicMobileMatchesTodayRouteImport.update({
    id: '/api/public/mobile/matches/today',
    path: '/api/public/mobile/matches/today',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMobileMatchesLiveRoute =
  ApiPublicMobileMatchesLiveRouteImport.update({
    id: '/api/public/mobile/matches/live',
    path: '/api/public/mobile/matches/live',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/dicas': typeof DashboardDicasRoute
  '/dashboard/jogos': typeof DashboardJogosRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/features': typeof ApiPublicFeaturesRoute
  '/api/public/debug/api-key': typeof ApiPublicDebugApiKeyRoute
  '/api/public/hooks/poll-live-notifications': typeof ApiPublicHooksPollLiveNotificationsRoute
  '/api/public/hooks/refresh-daily-matches': typeof ApiPublicHooksRefreshDailyMatchesRoute
  '/api/public/mobile/login': typeof ApiPublicMobileLoginRoute
  '/api/public/mobile/signup': typeof ApiPublicMobileSignupRoute
  '/api/public/mobile/tickets': typeof ApiPublicMobileTicketsRouteWithChildren
  '/api/public/team-image/$id': typeof ApiPublicTeamImageIdRoute
  '/api/public/mobile/matches/live': typeof ApiPublicMobileMatchesLiveRoute
  '/api/public/mobile/matches/today': typeof ApiPublicMobileMatchesTodayRoute
  '/api/public/mobile/notifications/live': typeof ApiPublicMobileNotificationsLiveRoute
  '/api/public/mobile/tickets/$id': typeof ApiPublicMobileTicketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/dicas': typeof DashboardDicasRoute
  '/dashboard/jogos': typeof DashboardJogosRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/features': typeof ApiPublicFeaturesRoute
  '/api/public/debug/api-key': typeof ApiPublicDebugApiKeyRoute
  '/api/public/hooks/poll-live-notifications': typeof ApiPublicHooksPollLiveNotificationsRoute
  '/api/public/hooks/refresh-daily-matches': typeof ApiPublicHooksRefreshDailyMatchesRoute
  '/api/public/mobile/login': typeof ApiPublicMobileLoginRoute
  '/api/public/mobile/signup': typeof ApiPublicMobileSignupRoute
  '/api/public/mobile/tickets': typeof ApiPublicMobileTicketsRouteWithChildren
  '/api/public/team-image/$id': typeof ApiPublicTeamImageIdRoute
  '/api/public/mobile/matches/live': typeof ApiPublicMobileMatchesLiveRoute
  '/api/public/mobile/matches/today': typeof ApiPublicMobileMatchesTodayRoute
  '/api/public/mobile/notifications/live': typeof ApiPublicMobileNotificationsLiveRoute
  '/api/public/mobile/tickets/$id': typeof ApiPublicMobileTicketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/dicas': typeof DashboardDicasRoute
  '/dashboard/jogos': typeof DashboardJogosRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/features': typeof ApiPublicFeaturesRoute
  '/api/public/debug/api-key': typeof ApiPublicDebugApiKeyRoute
  '/api/public/hooks/poll-live-notifications': typeof ApiPublicHooksPollLiveNotificationsRoute
  '/api/public/hooks/refresh-daily-matches': typeof ApiPublicHooksRefreshDailyMatchesRoute
  '/api/public/mobile/login': typeof ApiPublicMobileLoginRoute
  '/api/public/mobile/signup': typeof ApiPublicMobileSignupRoute
  '/api/public/mobile/tickets': typeof ApiPublicMobileTicketsRouteWithChildren
  '/api/public/team-image/$id': typeof ApiPublicTeamImageIdRoute
  '/api/public/mobile/matches/live': typeof ApiPublicMobileMatchesLiveRoute
  '/api/public/mobile/matches/today': typeof ApiPublicMobileMatchesTodayRoute
  '/api/public/mobile/notifications/live': typeof ApiPublicMobileNotificationsLiveRoute
  '/api/public/mobile/tickets/$id': typeof ApiPublicMobileTicketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/reset-password'
    | '/dashboard/configuracoes'
    | '/dashboard/dicas'
    | '/dashboard/jogos'
    | '/dashboard/notificacoes'
    | '/dashboard/usuarios'
    | '/dashboard/'
    | '/api/public/features'
    | '/api/public/debug/api-key'
    | '/api/public/hooks/poll-live-notifications'
    | '/api/public/hooks/refresh-daily-matches'
    | '/api/public/mobile/login'
    | '/api/public/mobile/signup'
    | '/api/public/mobile/tickets'
    | '/api/public/team-image/$id'
    | '/api/public/mobile/matches/live'
    | '/api/public/mobile/matches/today'
    | '/api/public/mobile/notifications/live'
    | '/api/public/mobile/tickets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/dashboard/configuracoes'
    | '/dashboard/dicas'
    | '/dashboard/jogos'
    | '/dashboard/notificacoes'
    | '/dashboard/usuarios'
    | '/dashboard'
    | '/api/public/features'
    | '/api/public/debug/api-key'
    | '/api/public/hooks/poll-live-notifications'
    | '/api/public/hooks/refresh-daily-matches'
    | '/api/public/mobile/login'
    | '/api/public/mobile/signup'
    | '/api/public/mobile/tickets'
    | '/api/public/team-image/$id'
    | '/api/public/mobile/matches/live'
    | '/api/public/mobile/matches/today'
    | '/api/public/mobile/notifications/live'
    | '/api/public/mobile/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/reset-password'
    | '/dashboard/configuracoes'
    | '/dashboard/dicas'
    | '/dashboard/jogos'
    | '/dashboard/notificacoes'
    | '/dashboard/usuarios'
    | '/dashboard/'
    | '/api/public/features'
    | '/api/public/debug/api-key'
    | '/api/public/hooks/poll-live-notifications'
    | '/api/public/hooks/refresh-daily-matches'
    | '/api/public/mobile/login'
    | '/api/public/mobile/signup'
    | '/api/public/mobile/tickets'
    | '/api/public/team-image/$id'
    | '/api/public/mobile/matches/live'
    | '/api/public/mobile/matches/today'
    | '/api/public/mobile/notifications/live'
    | '/api/public/mobile/tickets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicFeaturesRoute: typeof ApiPublicFeaturesRoute
  ApiPublicDebugApiKeyRoute: typeof ApiPublicDebugApiKeyRoute
  ApiPublicHooksPollLiveNotificationsRoute: typeof ApiPublicHooksPollLiveNotificationsRoute
  ApiPublicHooksRefreshDailyMatchesRoute: typeof ApiPublicHooksRefreshDailyMatchesRoute
  ApiPublicMobileLoginRoute: typeof ApiPublicMobileLoginRoute
  ApiPublicMobileSignupRoute: typeof ApiPublicMobileSignupRoute
  ApiPublicMobileTicketsRoute: typeof ApiPublicMobileTicketsRouteWithChildren
  ApiPublicTeamImageIdRoute: typeof ApiPublicTeamImageIdRoute
  ApiPublicMobileMatchesLiveRoute: typeof ApiPublicMobileMatchesLiveRoute
  ApiPublicMobileMatchesTodayRoute: typeof ApiPublicMobileMatchesTodayRoute
  ApiPublicMobileNotificationsLiveRoute: typeof ApiPublicMobileNotificationsLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usuarios': {
      id: '/dashboard/usuarios'
      path: '/usuarios'
      fullPath: '/dashboard/usuarios'
      preLoaderRoute: typeof DashboardUsuariosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notificacoes': {
      id: '/dashboard/notificacoes'
      path: '/notificacoes'
      fullPath: '/dashboard/notificacoes'
      preLoaderRoute: typeof DashboardNotificacoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jogos': {
      id: '/dashboard/jogos'
      path: '/jogos'
      fullPath: '/dashboard/jogos'
      preLoaderRoute: typeof DashboardJogosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dicas': {
      id: '/dashboard/dicas'
      path: '/dicas'
      fullPath: '/dashboard/dicas'
      preLoaderRoute: typeof DashboardDicasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/features': {
      id: '/api/public/features'
      path: '/api/public/features'
      fullPath: '/api/public/features'
      preLoaderRoute: typeof ApiPublicFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/team-image/$id': {
      id: '/api/public/team-image/$id'
      path: '/api/public/team-image/$id'
      fullPath: '/api/public/team-image/$id'
      preLoaderRoute: typeof ApiPublicTeamImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/tickets': {
      id: '/api/public/mobile/tickets'
      path: '/api/public/mobile/tickets'
      fullPath: '/api/public/mobile/tickets'
      preLoaderRoute: typeof ApiPublicMobileTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/signup': {
      id: '/api/public/mobile/signup'
      path: '/api/public/mobile/signup'
      fullPath: '/api/public/mobile/signup'
      preLoaderRoute: typeof ApiPublicMobileSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/login': {
      id: '/api/public/mobile/login'
      path: '/api/public/mobile/login'
      fullPath: '/api/public/mobile/login'
      preLoaderRoute: typeof ApiPublicMobileLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-daily-matches': {
      id: '/api/public/hooks/refresh-daily-matches'
      path: '/api/public/hooks/refresh-daily-matches'
      fullPath: '/api/public/hooks/refresh-daily-matches'
      preLoaderRoute: typeof ApiPublicHooksRefreshDailyMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/poll-live-notifications': {
      id: '/api/public/hooks/poll-live-notifications'
      path: '/api/public/hooks/poll-live-notifications'
      fullPath: '/api/public/hooks/poll-live-notifications'
      preLoaderRoute: typeof ApiPublicHooksPollLiveNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/api-key': {
      id: '/api/public/debug/api-key'
      path: '/api/public/debug/api-key'
      fullPath: '/api/public/debug/api-key'
      preLoaderRoute: typeof ApiPublicDebugApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/tickets/$id': {
      id: '/api/public/mobile/tickets/$id'
      path: '/$id'
      fullPath: '/api/public/mobile/tickets/$id'
      preLoaderRoute: typeof ApiPublicMobileTicketsIdRouteImport
      parentRoute: typeof ApiPublicMobileTicketsRoute
    }
    '/api/public/mobile/notifications/live': {
      id: '/api/public/mobile/notifications/live'
      path: '/api/public/mobile/notifications/live'
      fullPath: '/api/public/mobile/notifications/live'
      preLoaderRoute: typeof ApiPublicMobileNotificationsLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/matches/today': {
      id: '/api/public/mobile/matches/today'
      path: '/api/public/mobile/matches/today'
      fullPath: '/api/public/mobile/matches/today'
      preLoaderRoute: typeof ApiPublicMobileMatchesTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/matches/live': {
      id: '/api/public/mobile/matches/live'
      path: '/api/public/mobile/matches/live'
      fullPath: '/api/public/mobile/matches/live'
      preLoaderRoute: typeof ApiPublicMobileMatchesLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardDicasRoute: typeof DashboardDicasRoute
  DashboardJogosRoute: typeof DashboardJogosRoute
  DashboardNotificacoesRoute: typeof DashboardNotificacoesRoute
  DashboardUsuariosRoute: typeof DashboardUsuariosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardDicasRoute: DashboardDicasRoute,
  DashboardJogosRoute: DashboardJogosRoute,
  DashboardNotificacoesRoute: DashboardNotificacoesRoute,
  DashboardUsuariosRoute: DashboardUsuariosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiPublicMobileTicketsRouteChildren {
  ApiPublicMobileTicketsIdRoute: typeof ApiPublicMobileTicketsIdRoute
}

const ApiPublicMobileTicketsRouteChildren: ApiPublicMobileTicketsRouteChildren =
  {
    ApiPublicMobileTicketsIdRoute: ApiPublicMobileTicketsIdRoute,
  }

const ApiPublicMobileTicketsRouteWithChildren =
  ApiPublicMobileTicketsRoute._addFileChildren(
    ApiPublicMobileTicketsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicFeaturesRoute: ApiPublicFeaturesRoute,
  ApiPublicDebugApiKeyRoute: ApiPublicDebugApiKeyRoute,
  ApiPublicHooksPollLiveNotificationsRoute:
    ApiPublicHooksPollLiveNotificationsRoute,
  ApiPublicHooksRefreshDailyMatchesRoute:
    ApiPublicHooksRefreshDailyMatchesRoute,
  ApiPublicMobileLoginRoute: ApiPublicMobileLoginRoute,
  ApiPublicMobileSignupRoute: ApiPublicMobileSignupRoute,
  ApiPublicMobileTicketsRoute: ApiPublicMobileTicketsRouteWithChildren,
  ApiPublicTeamImageIdRoute: ApiPublicTeamImageIdRoute,
  ApiPublicMobileMatchesLiveRoute: ApiPublicMobileMatchesLiveRoute,
  ApiPublicMobileMatchesTodayRoute: ApiPublicMobileMatchesTodayRoute,
  ApiPublicMobileNotificationsLiveRoute: ApiPublicMobileNotificationsLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
